"""Create admin calon pengundi tables

Revision ID: 87742c052f33
Revises:
Create Date: 2026-05-10 10:09:24.897343

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "87742c052f33"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin",
        sa.Column("idAdmin", sa.String(length=3), nullable=False),
        sa.Column("namaAdmin", sa.String(length=30), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("idAdmin"),
    )
    op.create_table(
        "calon",
        sa.Column("idCalon", sa.String(length=3), nullable=False),
        sa.Column("namaCalon", sa.String(length=20), nullable=True),
        sa.Column("gambar", sa.String(length=100), nullable=True),
        sa.Column("moto", sa.String(length=100), nullable=True),
        sa.Column("idAdmin", sa.String(length=3), nullable=True),
        sa.ForeignKeyConstraint(
            ["idAdmin"],
            ["admin.idAdmin"],
        ),
        sa.PrimaryKeyConstraint("idCalon"),
    )
    op.create_table(
        "pengundi",
        sa.Column("idPengundi", sa.String(length=4), nullable=False),
        sa.Column("namaPengundi", sa.String(length=30), nullable=True),
        sa.Column("idCalon", sa.String(length=3), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["idCalon"],
            ["calon.idCalon"],
        ),
        sa.PrimaryKeyConstraint("idPengundi"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pengundi")
    op.drop_table("calon")
    op.drop_table("admin")
    # ### end Alembic commands ###
