"""Add gambar_public_id to Calon

Revision ID: cfed696f69d7
Revises: 87742c052f33
Create Date: 2026-05-13 17:38:05.905624

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "cfed696f69d7"
down_revision = "87742c052f33"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("calon", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("gambar_public_id", sa.String(length=255), nullable=True)
        )
        batch_op.alter_column(
            "gambar",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.Text(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("calon", schema=None) as batch_op:
        batch_op.alter_column(
            "gambar",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(length=100),
            existing_nullable=True,
        )
        batch_op.drop_column("gambar_public_id")

    # ### end Alembic commands ###
